project:
  type: website

website:
  title: "Bertrand Wilden"
  site-url: "https://www.bwilden.com"
  description: "Bertrand Wilden's Blog"
  navbar:
    right:
      - blog.qmd
      - icon: github
        href: https://github.com/bwilden
      - icon: rss
        href: https://www.bwilden.com/blog.xml
format:
  html:
    theme: lux
    css: styles.css



