project:
  type: website

website:
  title: "Bertrand Wilden"
  site-url: https://www.bwilden.com
  description: "Bertrand Wilden's Personal Website"
  navbar:
    right:
      - blog.qmd
      - icon: github
        href: https://github.com/bwilden
format:
  html:
    theme: lux
    css: styles.css



