project:
  type: website

website:
  title: "Bertrand Wilden"
  site-url: https://www.bwilden.com
  description: "Bertrand Wilden's Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/bwilden
      - icon: twitter
        href: https://twitter.com/bertrand_wilden
format:
  html:
    theme: lux
    css: styles.css



