---
title: "The NYC Rat Index"
page-layout: article
title-block-banner: true
execute: 
  message: false
  warning: false
  echo: false
---

```{r}
pacman::p_load(
  "leaflet",
  "tibble",
  "sf"
)
```

- New York City **Rat Index** percentiles by ZIP code
- Full blog post and methodology [here](https://www.bwilden.com/posts/nyc-rats/)

```{r}
rat_scores <- st_read(
  here::here("data", "rat_scores.shp"),
  quiet = TRUE
  ) |> 
  as_tibble()

pal <- colorNumeric(
  palette = "plasma",
  domain = rat_scores$zp_rt_p
)

pal_dir <- colorNumeric(
  palette = "plasma",
  domain = rat_scores$zp_rt_p,
  reverse = TRUE
)

l <- st_as_sf(rat_scores) |> 
  st_transform(crs = "WGS84") |> 
  leaflet() |> 
  addTiles()

labels <- sprintf(
  "<strong> ZIP Code: %s </strong> <br/>
  Rat Index: %s <br/> Percentile: %s",
  rat_scores$zip_cod,
  round(rat_scores$rat_scr, 2),
  round(rat_scores$zp_rt_p, 3)
) |>
  lapply(htmltools::HTML)

l |> 
  addPolygons(
    smoothFactor = .1, 
    fillOpacity = .8,
    fillColor = ~pal(zp_rt_p),
    weight = .1,
    highlightOptions = highlightOptions(weight = 5, color = "white"),
    label = labels,
    labelOptions = labelOptions(
      style = list(
        "font-weight" = "normal",
        padding = "3px 8px"
      ),
      textsize = "15px", direction = "auto"
    )
  ) |> 
  addLegend(
    pal = pal_dir,
    values = ~zp_rt_p, 
    opacity = 1,
    title = "Percentile", 
    position = "bottomright",
    labFormat = labelFormat(transform = function(x) sort(x, decreasing = TRUE))
  ) |> 
  addProviderTiles(providers$CartoDB.Positron)
```


